In [1]:
import os
base = "/kaggle/input/datasets/nizarkabbaj/poselift-pickle"
for dirname, dirs, files in os.walk(base):
    print(f"DIR: {dirname}")
    for f in files[:3]:
        print(f"  FILE: {f}")
    if files:
        print(f"  ... ({len(files)} files total)")

DIR: /kaggle/input/datasets/nizarkabbaj/poselift-pickle
DIR: /kaggle/input/datasets/nizarkabbaj/poselift-pickle/GT
  FILE: 1_222.npy
  FILE: 4_213.npy
  FILE: 1_240.npy
  ... (47 files total)
DIR: /kaggle/input/datasets/nizarkabbaj/poselift-pickle/Test
  FILE: 4_301.pkl
  FILE: 5_254.pkl
  FILE: 6_112.pkl
  ... (47 files total)
DIR: /kaggle/input/datasets/nizarkabbaj/poselift-pickle/Train
  FILE: 6_81.pkl
  FILE: 6_8.pkl
  FILE: 1_126.pkl
  ... (104 files total)


In [2]:
import os
import pickle
import numpy as np
import torch

# 1. Verify GPU
print("CUDA available:", torch.cuda.is_available())
print("GPU name:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "None")
print("PyTorch version:", torch.__version__)

# 2. Confirm file counts
base      = "/kaggle/input/datasets/nizarkabbaj/poselift-pickle"
train_dir = f"{base}/Train"
test_dir  = f"{base}/Test"
gt_dir    = f"{base}/GT"

train_files = sorted(os.listdir(train_dir))
test_files  = sorted(os.listdir(test_dir))
gt_files    = sorted(os.listdir(gt_dir))

print(f"\nTrain files : {len(train_files)}")
print(f"Test files  : {len(test_files)}")
print(f"GT files    : {len(gt_files)}")

# 3. Load one .pkl and inspect structure
sample_path = os.path.join(test_dir, test_files[0])
with open(sample_path, "rb") as f:
    sample = pickle.load(f)

print(f"\nLoaded      : {test_files[0]}")
print(f"Type        : {type(sample)}")
if isinstance(sample, dict):
    print(f"Keys        : {list(sample.keys())}")
elif isinstance(sample, list):
    print(f"Length      : {len(sample)}")
    print(f"First item  : {type(sample[0])}")
    if isinstance(sample[0], dict):
        print(f"First keys  : {list(sample[0].keys())}")

CUDA available: True
GPU name: Tesla T4
PyTorch version: 2.10.0+cu128

Train files : 104
Test files  : 47
GT files    : 47

Loaded      : 1_222.pkl
Type        : <class 'dict'>
Keys        : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90]


In [3]:
# Inspect one frame from the loaded sample
frame_0 = sample[0]
print(f"Type of frame_0     : {type(frame_0)}")

if isinstance(frame_0, dict):
    print(f"Keys                : {list(frame_0.keys())}")
    for k, v in frame_0.items():
        print(f"  [{k}] type={type(v).__name__}", end="")
        if hasattr(v, 'shape'):
            print(f"  shape={v.shape}", end="")
        elif isinstance(v, (list, tuple)):
            print(f"  len={len(v)}", end="")
        print()
elif isinstance(frame_0, (list, tuple)):
    print(f"Length              : {len(frame_0)}")
    print(f"First element       : {frame_0[0]}")

Type of frame_0     : <class 'dict'>
Keys                : []


In [4]:
# Find first non-empty frame
for frame_id, frame_data in sample.items():
    if frame_data:
        print(f"First non-empty frame : {frame_id}")
        print(f"Type                  : {type(frame_data)}")
        if isinstance(frame_data, dict):
            print(f"Keys                  : {list(frame_data.keys())}")
            for k, v in frame_data.items():
                print(f"  [{k}] type={type(v).__name__}", end="")
                if hasattr(v, 'shape'):
                    print(f"  shape={v.shape}", end="")
                elif isinstance(v, (list, tuple)):
                    print(f"  len={len(v)}", end="")
                print()
        break

First non-empty frame : 7
Type                  : <class 'dict'>
Keys                  : [3]
  [3] type=list  len=2


In [5]:
# Inspect the person entry in frame 7
frame_7 = sample[7]
person = frame_7[3]  # person ID 3

print(f"person type    : {type(person)}")
print(f"person len     : {len(person)}")
for i, item in enumerate(person):
    print(f"\n  item[{i}] type={type(item).__name__}", end="")
    if hasattr(item, 'shape'):
        print(f"  shape={item.shape}")
        print(f"  values={item}")
    elif isinstance(item, (list, tuple)):
        print(f"  len={len(item)}")
        print(f"  values={item}")
    else:
        print(f"  value={item}")

person type    : <class 'list'>
person len     : 2

  item[0] type=list  len=4
  values=[1150, 443, 1279, 634]

  item[1] type=ndarray  shape=(17, 3)
  values=[[5.175e+02 1.282e+03 4.761e-03]
 [4.550e+02 1.282e+03 9.850e-03]
 [4.938e+02 1.252e+03 4.200e-03]
 [4.430e+02 1.258e+03 2.332e-01]
 [4.460e+02 1.282e+03 1.008e-01]
 [4.640e+02 1.261e+03 4.861e-01]
 [4.968e+02 1.261e+03 6.182e-01]
 [5.415e+02 1.238e+03 1.106e-01]
 [5.505e+02 1.223e+03 7.305e-01]
 [5.890e+02 1.229e+03 1.163e-01]
 [5.860e+02 1.250e+03 7.432e-01]
 [5.475e+02 1.176e+03 1.686e-01]
 [5.835e+02 1.184e+03 2.710e-01]
 [6.310e+02 1.152e+03 9.625e-02]
 [6.310e+02 1.158e+03 1.093e-01]
 [6.010e+02 1.146e+03 6.458e-02]
 [6.280e+02 1.161e+03 4.630e-02]]
